### PR TITLE
My first contribution of str() and repr()

### PR DESCRIPTION
**Pull request by Zain3**
Adding the __str__() and __repr__() functions to the "Profiles" class to be able to print out basic Class information

### CODE REVIEW

**Comment by pmcdonal** [comment]
Since my issue triggered this, I guess I should say something. I'm not sure about the ideal "pull request" process. This looks like it shouldn't be harmful, but I'm not sure what it is going to print - my best guess is 
'<desilike.samples.profiles.Profiles object at 0x32cb31550>'
if I'm am correctly understanding that the added code is just:
    def __str__(self):
        return str(self)
... but this is what it already printed... 
If this was a branch in cosmodesi I think I could switch my local copy easily to include the change to see what it does... if I can do this easily even from Zain3... could someone tell me how? If there is any measurable overhead related to the "pull request" process, I would say it would be better to just not do it (the process), pushing directly master and fixing later if it doesn't work right...

**Comment by adematti** [comment]
Quickly: If we are > 1 contributors it's probably best to go for PR.
I typically google the things I want to do with git:
https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git

Could you be more specific about you'd like exactly, e.g. something simpler than https://github.com/cosmodesi/desilike/blob/74a0c43df7d1bd32fc131c02b9f73cac9194e811/desilike/samples/profiles.py#L598?

**Comment by pmcdonal** [comment]
Thanks - I didn't Google the right thing. So
git pull origin pull/28/head
appears to work, although now I'm wondering what I'd do to undo this if the change caused problems.
So it was worse than I imagined: 
print(result) 
now ends in:

RecursionError: maximum recursion depth exceeded while getting the str of an object

Below would be ok, although I'd like it better if in Jupyterlab it printed each parameter on its own line (which a direct call to to_stats does, but not this in print())
```
    def __str__(self):
        return str(self.to_stats(tablefmt="list"))
```

**Comment by pmcdonal** [comment]
(incidentally, my understanding is that __repr__ is supposed to give a complete representation of the object, not just some information, so probably shouldn't define that?)

**Comment by pmcdonal** [comment]
I guess it should be
```
    def __str__(self):
        return self.to_stats(tablefmt="pretty")
```
didn't see that option on first glance...

**Pull request closed without merging**
